from app.routers.auth import router as auth_router
from app.routers.models import router as models_router
from app.routers.arena import router as arena_router
from app.routers.orchestrator import router as orchestrator_router
from app.routers.audit import router as audit_router
from app.routers.sandbox import router as sandbox_router
from app.routers.wallet import router as wallet_router
from app.routers.creators import router as creators_router
from app.routers.registry import router as registry_router
from app.routers.recommendations import router as recommendations_router
from app.routers.assistant import router as assistant_router
from app.routers.gateway import router as gateway_router